config/routes.rb
Rails.application.routes.draw do
  root :to => 'landing_page#index'
  resources :products do
    resources :reviews, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true

  scope :most_reviewed, -> {(
    select("products.name, products.cost, products.origin, products.id, products.created_at, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    ).limit(3)}

    scope :most_recent, -> { order(created_at: :desc).limit(3) }

    scope :local, -> { where(origin: "USA")}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :product_id, :presence => true
  validates :author, :presence => true
  validates :content_body, :presence => true
  validates :rating, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
    @most_reviewed = Product.most_reviewed
    @most_recent = Product.most_recent
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to product_path(@product)
    else
      flash[:notice] = "Your product was not added."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:success] = "Update was successful"
        redirect_to product_path(@product)
      else
        flash[:danger] = "Was not able to update"
        render :edit
     end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

 def create
   @product = Product.find(params[:product_id])
   @review = @product.reviews.new(review_params)
   if @review.save
     flash[:notice] = "Review successfully added!"
     redirect_to product_path(@review.product)
   else
     flash[:notice] = "Your product was not added."
     render :new
   end
 end

 def edit
   @product = Product.find(params[:product_id])
   @review = @product.reviews.find(params[:id])
 end

 def update
   @product = Product.find(params[:product_id])
   @review = @product.reviews.find(params[:id])
   if @review.update(review_params)
     flash[:notice] = "Review successfully updated!"
     redirect_to product_path(@product)
   else
     flash[:notice] = "Your product was not added."
     render :edit
   end
 end

 def destroy
   @review = Review.find(params[:id])
   @review.destroy
   redirect_to product_path(@review.product)
 end

 private
   def review_params
     params.require(:review).permit(:author, :content_body, :rating)
   end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing_page/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Gabi's Book Store</h1>

    <p>
      We review books, please add yours to our collection.
    </p>
  </div>
  <div class="container">
      <h3>Most Reviewed Books:</h3>
      <% @most_reviewed.each do |review| %>
      <%= link_to review.name, product_path(review.id) %>
      <% end %>

      <h3>Recent Reviews:</h3>
      <% @most_recent.each do |product| %>
      <%= link_to product.name, product_path(product) %>
      <% end %>

      <h3><%= link_to "All Books", products_path%></h3>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>
<div class="well">
<%= form_for [ @product ] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> </br></br></br>
  <%= f.label :cost %>
  <%= f.text_field :cost %> </br></br></br>
  <%= f.label :origin %>
  <%= f.text_field :origin %> </br></br></br>
  <%= f.submit %>
<% end %>
</div>

app/views/products/edit.html.erb
<div class="container">


<%= render "form" %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="well">

  <h1>Books</h1>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>

  <h3><%= link_to "Add New", new_product_path %></h3>
  <h3><%= link_to "Home", root_path %></h3>
</div>
</div>

app/views/products/new.html.erb
<div class="well">

  <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="container">

  <div class ="well">
    <h4>Product: <%= @product.name %></h4>
    <h4>Cost: <%= @product.cost %></h4>
    <h4>Place of Origin: <%= @product.origin %></h4>
    <h4>Reviews:</h4>
    <ul>
      <% if @reviews.any? %>
        <% @reviews.each do |review| %>
          <li> <%= link_to review.content_body , edit_product_review_path(@product, review) %></li>
        <% end %>
        <% else %>
          <h5>No reviews</h5>
        <% end %>
    </ul>
  </div>

  <h3><%= link_to "Add Review", new_product_review_path(@product) %></h3>
  <h3><%= link_to "Edit Product", edit_product_path(@product) %></h3>
  <h3><%= link_to "Delete Product", product_path(@product),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></h3>

  <h3><%= link_to "Return to products", products_path %></h3>
</div>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  1<%= f.radio_button :rating, '1' %>
  2<%= f.radio_button :rating, '2' %>
  3<%= f.radio_button :rating, '3' %>
  4<%= f.radio_button :rating, '4' %>
  5<%= f.radio_button :rating, '5' %>

  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="well">
  <h1>Edit Review: <%= @review.content_body %> </h1>
  </div>
  <%= render 'form' %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="well">
    <h1>New review for <%= @product.name %></h1>
  </div>
<%= render 'form' %>

</div>